// This file was generated by gir (https://github.com/gtk-rs/gir @ 00040a2)
// from gir-files (https://github.com/gtk-rs/gir-files @ c47bea4)
// DO NOT EDIT

#![allow(non_camel_case_types, non_upper_case_globals, non_snake_case)]
#![allow(clippy::approx_constant, clippy::type_complexity, clippy::unreadable_literal)]
#![cfg_attr(feature = "dox", feature(doc_cfg))]

extern crate libc;
extern crate cairo_sys as cairo;
extern crate gdk_sys as gdk;
extern crate gdk_pixbuf_sys as gdk_pixbuf;
extern crate gio_sys as gio;
extern crate glib_sys as glib;
extern crate gobject_sys as gobject;
extern crate gtk_sys as gtk;

#[allow(unused_imports)]
use libc::{c_int, c_char, c_uchar, c_float, c_uint, c_double,
    c_short, c_ushort, c_long, c_ulong,
    c_void, size_t, ssize_t, intptr_t, uintptr_t, time_t, FILE};

#[allow(unused_imports)]
use glib::{gboolean, gconstpointer, gpointer, GType};

// Enums
pub type GtkLayerShellEdge = c_int;
pub const GTK_LAYER_SHELL_EDGE_LEFT: GtkLayerShellEdge = 0;
pub const GTK_LAYER_SHELL_EDGE_RIGHT: GtkLayerShellEdge = 1;
pub const GTK_LAYER_SHELL_EDGE_TOP: GtkLayerShellEdge = 2;
pub const GTK_LAYER_SHELL_EDGE_BOTTOM: GtkLayerShellEdge = 3;
pub const GTK_LAYER_SHELL_EDGE_ENTRY_NUMBER: GtkLayerShellEdge = 4;

pub type GtkLayerShellLayer = c_int;
pub const GTK_LAYER_SHELL_LAYER_BACKGROUND: GtkLayerShellLayer = 0;
pub const GTK_LAYER_SHELL_LAYER_BOTTOM: GtkLayerShellLayer = 1;
pub const GTK_LAYER_SHELL_LAYER_TOP: GtkLayerShellLayer = 2;
pub const GTK_LAYER_SHELL_LAYER_OVERLAY: GtkLayerShellLayer = 3;
pub const GTK_LAYER_SHELL_LAYER_ENTRY_NUMBER: GtkLayerShellLayer = 4;

#[link(name = "gtk-layer-shell")]
extern "C" {

    //=========================================================================
    // Other functions
    //=========================================================================
    pub fn gtk_layer_auto_exclusive_zone_enable(window: *mut gtk::GtkWindow);
    pub fn gtk_layer_init_for_window(window: *mut gtk::GtkWindow);
    pub fn gtk_layer_set_anchor(window: *mut gtk::GtkWindow, edge: GtkLayerShellEdge, anchor_to_edge: gboolean);
    pub fn gtk_layer_set_exclusive_zone(window: *mut gtk::GtkWindow, exclusive_zone: c_int);
    pub fn gtk_layer_set_keyboard_interactivity(window: *mut gtk::GtkWindow, interacitvity: gboolean);
    pub fn gtk_layer_set_layer(window: *mut gtk::GtkWindow, layer: GtkLayerShellLayer);
    pub fn gtk_layer_set_margin(window: *mut gtk::GtkWindow, edge: GtkLayerShellEdge, margin_size: c_int);
    pub fn gtk_layer_set_monitor(window: *mut gtk::GtkWindow, monitor: *mut gdk::GdkMonitor);
    pub fn gtk_layer_set_namespace(window: *mut gtk::GtkWindow, name_space: *const c_char);

}
