// This file was generated by gir (https://github.com/gtk-rs/gir)
// from gir-files (https://github.com/gtk-rs/gir-files)
// DO NOT EDIT

mod enums;
pub use self::enums::Edge;
pub use self::enums::Layer;

pub mod functions;

#[doc(hidden)]
pub mod traits {}
